---
name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.7]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3.0.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Test
      run: make test
