name: verify

on:
  push:
  pull_request:

env:
  GO_VERSION: 1.17.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
      - uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # v2.2.0
        with:
          go-version:  ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # v3.1.0
        timeout-minutes: 5
        with:
          version: v1.45.0
      - run: |
          go mod tidy
          git diff --exit-code
