name: verify

on:
  push:
  pull_request:

env:
  GO_VERSION: 1.17.7

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 #v2.2.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
<<<<<<< HEAD:.github/workflows/verify.yaml
        uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29 #v2.5.2
=======
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018 # v2.5.2
>>>>>>> a53ce78 (ci: use git hash for the actions):.github/workflows/verify.yml
        timeout-minutes: 5
        with:
          version: v1.44.2
